### ISSUE TITLE
Unable to add DefinedTags in new Secret

### ISSUE THREAD

**Issue by marknelsonjr1984** [oracle/oci-powershell-modules#106]
I am trying to create a New-OCIVaultSecret and add defined tags to match existing entries in my vault. I seem unable to add any tags. Can you tell me what I am doing wrong and provide an example on how to add? 

example of Tags I want to add: 

`$LabSecretInfo.DefinedTags  

Key                 Value
---                 -----
Lab-Secrets-Metadata    {[Function, WinRM]}
Lab-AccessControl {[SVC-Lab-Reader, allow], [Lab, all-users]}`

This is what I am Trying to do to Add but cannot get past various errors, specifically after I make the definedtags and try to add to my $CreateSecretDetails = New-Object Oci.VaultService.Models.CreateSecretDetails: 

#DefinedTags
$tags = New-Object 'System.Collections.Generic.Dictionary[String,object]'
$tags.Add('Lab-Secrets-Metadata','{[Function, WinRM]}')

`$tags

Key              Value
---              -----
Lab-Secrets-Metadata {[Function, WinRM]}`

#ADD to CreateSecret Details - various things I tried with no luck. 
$CreateSecretDetails.DefinedTags($tags)
$CreateSecretDetails.DefinedTags.Keys.Add($tags)
$CreateSecretDetails.DefinedTags.values.Add($tags)

**Comment by KartikShrikantHegde** [comment]
Hi @marknelsonjr1984 ,

Thank you for reporting the issue. We will take a look and get back to you as soon as we can.

**Comment by KartikShrikantHegde** [comment]
Hi @marknelsonjr1984 ,

Please take a look at below, this is how you could add defined tags. 

`Import-Module OCI.PSModules.Vault
$CreateSecretDetails = New-Object Oci.VaultService.Models.CreateSecretDetails
$tags=[System.Collections.Generic.Dictionary[string,object]]::new()
$CreateSecretDetails.DefinedTags = [System.Collections.Generic.Dictionary[string,string]]::new()
$tags.abc=@("def")
$CreateSecretDetails
`

Thanks.

**Comment by marknelsonjr1984** [comment]
Thanks for the help! You can close this ticket.
