### ISSUE TITLE
Invoke-OCIUsageapiRequestSummarizedUsages 

### ISSUE THREAD

**Issue by jtp64** [oracle/oci-powershell-modules#113]
Would like to see some examples using this command. Cannot determine how to frame the syntax that goes with this command and the "-RequestSummarizedUsagesDetails" option.

**Comment by KartikShrikantHegde** [comment]
Hi @jtp64,

We will work on creating a sample for this API. Once it's available, I will provide the link here.

Thanks.

**Comment by KartikShrikantHegde** [comment]
Hi @jtp64 ,

We have created a sample script for the above. Here is the link - https://github.com/oracle/oci-powershell-modules/blob/master/Examples/RequestSummarizedUsages.ps1

Please give it a try and let us know for any issues.

Thanks.

**Comment by KartikShrikantHegde** [comment]
Hi @jtp64 , I will be closing this issue since we haven't heard from you in a while. Please feel free to re-open the issue, if the example doesn't work.

Thank you.
