### ISSUE TITLE
Update Secret Content Not Accepting Special Characters which are accepted. 

### ISSUE THREAD

**Issue by marknelsonjr1984** [oracle/oci-powershell-modules#116]
I get the following error when running this code. 
....
$SecretBundleUpdate = "R0ta!teM3Again"
$UpdateSecretDetails = New-Object Oci.VaultService.Models.UpdateSecretDetails
$SecretContentDetails = New-Object Oci.VaultService.Models.Base64SecretContentDetails
$UpdateSecretDetails.SecretContent = $SecretContentDetails
$UpdateSecretDetails.SecretContent.Content = $($SecretBundleUpdate)

....

  Update-OCIVaultSecret -SecretId $SecretID -UpdateSecretDetails $Updat …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error returned by Vaults Service. Http Status Code: 400. ServiceCode: InvalidParameter. OpcRequestId: /3AE9A00E53305B439FCFB4708F8F3BC6/327A9D9340D64EA59C2C4CE88B994D65. Message: content has an invalid format Operation Name:
     | UpdateSecret TimeStamp: 2022-10-17T19:50:19.699Z Client Version: Oracle-DotNetSDK/46.0.0 (Win32NT/10.0.22000.0; .NET 6.0.8)  Oracle-PowerShell/42.0.0  Request Endpoint: PUT
     | https://vaults.us-phoenix-1.oci.oraclecloud.com/20180608/secrets/ocid1.vaultsecret.oc1.phx.amaaaaaas....For details on this operation's requirements, see
     | https://docs.oracle.com/iaas/api/#/en/secretmgmt/20180608/Secret/UpdateSecret. Get more information on a failing request by using the -Verbose or -Debug flags. See
     | https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/powershellconcepts.htm#powershellconcepts_topic_logging For more information about resolving this error, see
     | https://docs.oracle.com/en-us/iaas/Content/API/References/apierrors.htm#apierrors_400__400_invalidparameter If you are unable to resolve this Vaults issue, please contact Oracle support and provide them this full error message.

however in the console the value in $SecretBundleUpdate is accepted. 

If I make the contents without a special character it updates just fine. example below
$SecretBundleUpdate = "R0tateM3Again"

I confirmed the $SecretBundleUpdate to be a string object. is this a bug? please advise. Thanks!

**Comment by github-anurag** [comment]
@marknelsonjr1984 
I think the content should be in a Base64 string.
In C# we would expect the content to be inputted as:-
`Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(text));` 

Can you try doing something similar in this PWSH script and see if it works?

**Comment by github-anurag** [comment]
Something like this perhaps:-
```
$SecretBundleUpdate = "R0ta!teM3Again"
$encodedBytes = [System.Text.Encoding]::UTF8.GetBytes($SecretBundleUpdate)
$encodedText = [System.Convert]::ToBase64String($encodedBytes)
```

**Comment by github-anurag** [comment]
Refer the docs: https://docs.oracle.com/en-us/iaas/api/#/en/secretmgmt/20180608/datatypes/Base64SecretContentDetails and check the `content` attribute which states that content should be `The base64-encoded content of the secret.`

**Comment by marknelsonjr1984** [comment]
Yep That was it! Thanks for the fast response. you can mark this as closed.
