### ISSUE TITLE
OCI.PSModules.Core 47.3.0 problem creating ENCRYPTED private key

### ISSUE THREAD

**Issue by cadayton** [oracle/oci-powershell-modules#126]
The following cmdlet from OCI.PSModules.Core 47.3.0

Get-OCIComputeInstancesList -CompartmentId $cid 

This command is returning following error.

Get-OCIComputeInstancesList: problem creating ENCRYPTED private key: System.NullReferenceException: Object reference not set to an instance of an object. at Org.BouncyCastle.OpenSsl.PemReader.ReadPrivateKey(PemObject pemObject) in /_/crypto/src/openssl/PEMReader.cs:line 342

Get-OCIComputeInstance cmdlet returns the same error as well

**Comment by cadayton** [comment]
With further trouble shooting, I've determine Get-OCIComputeInstance and Get-OCIComputeInstancesList cmdlet has issues reading the default profile in the config file.

I created a second profile in the file config called, [dogmeat] along with the 'pass_phrase' attribute and the command executed without any issues.

As for the Get-OCIComputeInstancesList cmdlet, it requires a parameter named 'CompartmentId'.   I'm not sure where to find the needed compartmentID value.

**Comment by github-anurag** [comment]
@cadayton 
Can you share the oci config profile you are using.
Please make sure the config file follows the structure mentioned here: https://docs.oracle.com/en-us/iaas/Content/API/Concepts/sdkconfig.htm 

The `CompartmentId` is the compartment where you want command to look for instance. This can also be your tenancy ID. This id can be found by clicking on the tenancy or compartment you want to use. Refer section `Where to Get the Tenancy's OCID and User's OCID` at https://docs.oracle.com/en-us/iaas/Content/API/Concepts/apisigningkey.htm 

A config file example:-
```
[DEFAULT]
user = <USER OCID>
fingerprint = <Key fingerprint>
tenancy = <Tenancy OCID>
region = <Region ID>
key_file = <Path to key file>
```
Refer https://docs.oracle.com/en-us/iaas/Content/API/Concepts/apisigningkey.htm on generating a key.

Also, the way you might be using the Environment variable might be incorrect. Recommended way of using the environment variable.
```
 $Env:OCI_COMPARTMENT_ID = "ocid1.tenancy.oc1.."
 Get-OCIComputeInstancesList -CompartmentId $Env:OCI_COMPARTMENT_ID
```

**Comment by cadayton** [comment]
Hi, Anurag

Below is the syntax of the file, config that I'm using. I did figure out that -CompartmentID is simply the Tenancy OCID value.

No environmental variables are defined so this can be ruled out.

If I use the parameter '-Profile 'dogmeat'', the cmdlets work as expected. If remove, the dogmeat profile from config, then from some reason the cmdlets are not finding the key_file attribute.

Also, if the pass_phrase isn't correct the cmdlets will fail too. I'm ok with this because I will simply encrypt/decrypt the config as needed.

[Default]
user = ocid1.user.oc1...
fingerprint = xx:xx
tenancy = ocid1.tenancy.oc1...
region = us-sanjose-1
key_file = /home/cadayton/.oci/oci_api_key.pem
pass_phrase = ###############

[dogmeat]
user = ocid1.user.oc1...
fingerprint = xx:xx
tenancy = ocid1.tenancy.oc1...
region = us-sanjose-1
key_file = /home/cadayton/.oci/oci_api_key.pempass_phrase = ###########

------- Original Message -------

**Comment by github-anurag** [comment]
@cadayton 
Can you try renaming `Default`to `DEFAULT` and see if it helps.

**Comment by cadayton** [comment]
Thanks!!! Changing from 'Default' to 'DEFAULT' has resolved the issue.

PS /home/cadayton> Get-OCIComputeInstance -InstanceId $iid

AvailabilityDomain : KOrY:US-SANJOSE-1-AD-1
CapacityReservationId :
....
------- Original Message -------

**Comment by github-anurag** [comment]
Glad it worked.
