### ISSUE TITLE
Problem Mounting Block Volumes - Mount-OCIComputeVolume using Oci.CoreService.Models.AttachVolumeDetails 

### ISSUE THREAD

**Issue by WPHJS** [oracle/oci-powershell-modules#38]
I'm having an issue mounting blockvolumes to instances using Mount-OCIComputeVolume and Oci.CoreService.Models.AttachVolumeDetails .

It looks like AttachVolumeDetails is missing a required property of Type , it shows as required here: 
https://docs.oracle.com/en-us/iaas/tools/dotnet/2.0.0/api/Oci.CoreService.Models.AttachVolumeDetails.html
Type | System.String | The type of volume. The only supported values are 'iscsi' and 'paravirtualized'

Output of object from 13.1.0 is missing that property:
New-Object -TypeName Oci.CoreService.Models.AttachVolumeDetails

Device      :
DisplayName :
InstanceId  :
IsReadOnly  :
IsShareable :
VolumeId    :

Attempting to mount a volume fails:

PS C:\Users\wphjs> $AttachVolumeDetails = New-Object -TypeName Oci.CoreService.Models.AttachVolumeDetails
PS C:\Users\wphjs> $AttachVolumeDetails.InstanceId = 'ocid1.instance.oc1.iad.REDACTED'
PS C:\Users\wphjs> $AttachVolumeDetails.VolumeId = 'ocid1.volume.oc1.iad.REDACTED'
PS C:\Users\wphjs> $MountOutput = Mount-OCIComputeVolume -AttachVolumeDetails $AttachVolumeDetails
Mount-OCIComputeVolume: Unable to process JSON input

**Comment by github-anurag** [comment]
Hi @WPHJS,
I think you will need to use either Oci.CoreService.Models.AttachParavirtualizedVolumeDetails or Oci.CoreService.Models.AttachIScsiVolumeDetails for this.

**Comment by WPHJS** [comment]
Hello @github-anurag ,

Can you clarify, use in what way?

In this case I'm trying to mount an iscsi volume. Looking at Oci.CoreService.Models.AttachIScsiVolumeDetails , the only property is useChap, no properties to provide the InstanceId and VolumeId of which I want to attach. 

https://docs.oracle.com/en-us/iaas/tools/dotnet/2.0.0/api/Oci.CoreService.Models.AttachIScsiVolumeDetails.html

If AttachIScsiVolumeDetails is meant to be used as the object supplied to a property, like CreateVnicDetails is put into LaunchInstanceDetails.CreateVnicDetails , I am not seeing how to do that.

**Comment by github-anurag** [comment]
@WPHJS 
Glad to know it works for you. Can I close this issue :)

**Comment by WPHJS** [comment]
No issue, operator error :)
