### ISSUE TITLE
Get-OCIVirtualNetworkSecurityList doesn't return security rules

### ISSUE THREAD

**Issue by vincents1** [oracle/oci-powershell-modules#47]
Here is the output from Get-OCIVirtualNetworkSecurityList. The corresponding OCI CLI returns the security rules but Get-OCIVirtualNetworkSecurityList doesn't. 

PS C:\temp> Get-OCIVirtualNetworkSecurityList -SecurityListId ocid1.securitylist.oc1.phx.aaaaaaaa4fgdmge4jhajeyirtoqxvt42pq5lcigrio4tn23uahj6naxxxx

CompartmentId        : ocid1.compartment.oc1..aaaaaaaak32w4qwxitd5wmirgiyyivvxp3idzklqgwlqtq3gg3qu3yxxxxxxx
DefinedTags          : {}
DisplayName          : XXXXXXXXXX
EgressSecurityRules  : {Oci.CoreService.Models.EgressSecurityRule, Oci.CoreService.Models.EgressSecurityRule,
                       Oci.CoreService.Models.EgressSecurityRule, Oci.CoreService.Models.EgressSecurityRule…}
FreeformTags         : {}
Id                   : ocid1.securitylist.oc1.phx.aaaaaaaa4fgdmge4jhajeyirtoqxvt42pq5lcigrio4tn23uahXXXXXXX
IngressSecurityRules : {Oci.CoreService.Models.IngressSecurityRule, Oci.CoreService.Models.IngressSecurityRule,
                       Oci.CoreService.Models.IngressSecurityRule, Oci.CoreService.Models.IngressSecurityRule…}
LifecycleState       : Available
TimeCreated          : 2/9/2019 2:32:12 AM
VcnId                : ocid1.vcn.oc1.phx.aaaaaaaacklqz42zeqgwxvvhlgq3qztpfxfr4u3h7kep35cjpg7xxxxxxx

**Comment by joshunter** [comment]
Hi @vincents1, the object you see should contain the rules. In order to print the rules you may have to dot-reference them e.g.: 
> $obj = Get-OCIVirtualNetworkSecurityList -SecurityListId ocid1.securitylist.oc1....
> $obj.IngressSecurityRules
or
> (Get-OCIVirtualNetworkSecurityList -SecurityListId ocid1.securitylist.oc1....).EgressSecurityRules

Let me know if this is still an issue.

**Comment by vincents1** [comment]
Hi @joshunter, Thank you for the help. The dot-reference works! I'm closing the comment.
