### ISSUE TITLE
New-OCIvaultSecret CreateSecretDetails: 

### ISSUE THREAD

**Issue by marknelsonjr1984** [oracle/oci-powershell-modules#83]
I cant seem to figure out what is actually accepted in the parameter createsecretdetails in the New-OCIVaultSecret CMDLet, or how to dissect whats in the oci.vaultservice.models.createsecretsdetails type. Any help would be very appreciated! 

-CreateSecretDetails
Request to create a new secret.

Type: Oci.VaultService.Models.CreateSecretDetails
Parameter Sets: (All)
Aliases: None

Required: True
Position: Named
Default value: None
Accept pipeline input: True (ByPropertyName)
Accept wildcard characters: False

**Comment by marknelsonjr1984** [comment]
Hey @joshunter thanks for the reply, made some progress but stuck on this part now. 

referencing your example above SecretContent also needs a psobject, so i did so, however when I run to create my secret I get "New-OCIVaultSecret: Invalid typeId provided " 

one thing i noticed when looking at the API reference: https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/vault/models/oci.vault.models.SecretContentDetails.html and https://github.com/oracle/oci-dotnet-sdk/blob/master/Vault/models/SecretContentDetails.cs I noticed the object is missing 'content type' which is required. is this a bug? 

`PS C:\Users\MARKSNEL\Documents\Cloudlab\iss\windows\application-tools-services\GSIV> $secretcontentdetails = new-object Oci.VaultService.Models.SecretContentDetails
PS C:\Users\MARKSNEL\Documents\Cloudlab\iss\windows\application-tools-services\GSIV> $secretcontentdetails |gm 

   TypeName: Oci.VaultService.Models.SecretContentDetails

Name        MemberType Definition
----        ---------- ----------
Equals      Method     bool Equals(System.Object obj)
GetHashCode Method     int GetHashCode()
GetType     Method     type GetType()
ToString    Method     string ToString()
Name        Property   string Name {get;set;}
Stage       Property   System.Nullable[Oci.VaultService.Models.SecretContentDetails+StageEnum] Stage {get;set;}`


im trying to add some test secrets in this is what I have so far: `
#required class attribute of content_type missing based on: https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/vault/models/oci.vault.models.SecretContentDetails.html 
$secretcontentdetails = new-object Oci.VaultService.Models.SecretContentDetails

#String to Base64 
$Text = "ThIsi5()nly@t3st"
$Bytes = [System.Text.Encoding]::Unicode.GetBytes($Text)
$EncodedText =[Convert]::ToBase64String($Bytes)
$secretcontentdetails.Name = $EncodedText
$secretcontentdetails.Stage = "CURRENT"

#Required class oci.vault.models.CreateSecretDetails Attributes per API Reference: https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/vault/models/oci.vault.models.CreateSecretDetails.html#oci.vault.models.CreateSecretDetails.secret_content
$secretdetails = new-object Oci.VaultService.Models.CreateSecretDetails   
$secretdetails.CompartmentId = "ocid1.compartment.oc1..foobar"
$secretdetails.SecretContent = $secretcontentdetails
$secretdetails.SecretName    = "marksnelpowershelltest"
$secretdetails.VaultId       = "ocid1.vault.oc1.phx.foobar"

new-ocivaultsecret -createsecretdetails $secretdetails 
`

**Comment by joshunter** [comment]
Hi @marknelsonjr1984, I was able to create a vault secret by using [Base64SecretContentDetails](https://github.com/oracle/oci-dotnet-sdk/blob/master/Vault/models/Base64SecretContentDetails.cs), which has the type hard-coded. However, I also had to specify the KeyId field in CreateSecretDetails which is not indicated as required but seems to be.

**Comment by marknelsonjr1984** [comment]
@joshunter Can I see an example of what you got working. I think that would really help me and others trying to adopt this module and oci service. Thanks!

**Comment by joshunter** [comment]
Sure, here's how I was able to add a secret:
```
Import-Module OCI.PSModules.Vault

$SecretContentDetails = New-Object Oci.VaultService.Models.Base64SecretContentDetails

$Content = "Powershell!"
$ContentEncoded = [System.Text.Encoding]::UTF8.GetBytes($Content)
$ContentBase64 = [System.Convert]::ToBase64String($ContentEncoded)

$SecretContentDetails.Content = $ContentBase64
$SecretContentDetails.Name = "SecretName"
$SecretContentDetails.Stage = "CURRENT"

$CreateSecretDetails = New-Object Oci.VaultService.Models.CreateSecretDetails

$CreateSecretDetails.CompartmentId = "ocid1.compartment.oc1..."

# OCID of a 128 bit AES key in the vault where this secret will be stored.
$CreateSecretDetails.KeyId = "ocid1.key.oc1..."

# The object we created above.
$CreateSecretDetails.SecretContent = $SecretContentDetails

# This name will be seen when secrets are listed.
$CreateSecretDetails.SecretName = "SecretName"

# OCID of the vault where this secret will be stored.
$CreateSecretDetails.VaultId = "ocid1.vault.oc1..."

New-OCIVaultSecret -CreateSecretDetails $CreateSecretDetails
```
The only thing to keep in mind is that you'll need a key, which you can either find with [Get-OCIKeymanagementKeysList](https://docs.oracle.com/en-us/iaas/tools/powershell/30.0.0/articles/Get-OCIKeymanagementKeysList.html) or generate with [New-OCIKeymanagementKey](https://docs.oracle.com/en-us/iaas/tools/powershell/30.0.0/articles/New-OCIKeymanagementKey.html). Both of these cmdlets come from the `OCI.PSModules.Keymanagement` module.

**Comment by marknelsonjr1984** [comment]
thanks for the help! you can close this issue and mark as resolved.
