### ISSUE TITLE
Get-OCILoadbalancersList: Exception has been thrown by the target of an invocation

### ISSUE THREAD

**Issue by vincents1** [oracle/oci-powershell-modules#84]
This works without -all flag:
$balancers =Get-OCILoadbalancersList  -CompartmentId "ocid1.compartment.oc1xxxx" -Region "us-phoenix-1" 

Adding -all flag, it generates exceptions. If I use -limit flag, it works up to 438 page limit. 

$balancers =Get-OCILoadbalancersList  -CompartmentId "ocid1.compartment.oc1xxxx" -Region "us-phoenix-1" -all
Get-OCILoadbalancersList: Exception has been thrown by the target of an invocation.

Is this related to memory/array size? Any workaround?
Thanks!

**Comment by jodoglevy** [comment]
@vincents1  thanks for reporting. Can you copy paste the full exception stack trace so we can better investigate?

**Comment by joshunter** [comment]
@vincents1, thanks again for raising this issue. It turned out that the modules were not excepting the enum value that was being returned and that caused the cmdlet to fail. The latest release will accept unknown enum values and no longer fail for this type of issue.
